name: ci

on:
  push:
    branches:
      - main
      - next

permissions:
  contents: write
  issues: write
  pages: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: Continuous Release
    uses: ./.github/workflows/release.yml
    secrets: inherit

  build_docs:
    name: Build Documentation
    uses: ./.github/workflows/build-docs.yml
    secrets: inherit

  publish_docs:
    name: Publish Docs to GitHub Pages
    uses: ./.github/workflows/publish-docs.yml
    secrets: inherit
    needs:
      - build_docs
    if: needs.build_docs.result == 'success'
