name: ci

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next

permissions:
  contents: write
  issues: write
  pages: write
  pull-requests: write
  id-token: write

jobs:
  version-check:
    name: Version check
    uses: ./.github/workflows/version-check.yml
    secrets: inherit
