name: ci

on:
  push:
    branches:
      - main
      - next

permissions:
  contents: write
  issues: write
  pages: write
  pull-requests: write
  id-token: write

jobs:
  version_check:
    name: Version check
    uses: ./.github/workflows/version-check.yml
    secrets: inherit

  release:
    name: Release
    uses: ./.github/workflows/release.yml
    secrets: inherit
    needs:
      - version_check
    if: ${{ needs.version_check.status == 'success' }}

  test_coverage:
    name: Upload results to Codecov on Release
    uses: ./.github/workflows/test.yml
    secrets: inherit
    needs:
      - release
    if: ${{ needs.release.status == 'success' }}

  docs_check:
    name: Docs Check
    uses: ./.github/workflows/docs-check.yml
    secrets: inherit
    needs:
      - release
    if: success() || failure() # Same as '!cancelled()'

  debug_needs:
    name: Debug Needs Context
    runs-on: ubuntu-latest
    needs:
      - docs_check
    if: success() || failure()
    steps:
      - name: Debug Needs Context
        run: echo '${{ toJSON(needs) }}'

  build_docs:
    name: Build Documentation
    uses: ./.github/workflows/build-docs.yml
    secrets: inherit
    needs:
      - docs_check
    if: ${{ needs.docs_check.outputs && needs.docs_check.outputs.success == 'true' }}

  publish_docs:
    name: Publish Docs to GitHub Pages
    uses: ./.github/workflows/publish-docs.yml
    secrets: inherit
    needs:
      - build_docs
    if: success()
