name: docs-check

on:
  workflow_call:

jobs:
  check_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure full commit history

      - name: Check for documentation commits
        id: check_docs
        run: |
          # Get all commit messages in the current push
          COMMITS=$(git log --pretty=%s ${{ github.event.before }}..${{ github.sha }} 2>/dev/null || echo "")

          # Check if any commit includes "docs:" or "docs(anything):"
          if echo "$COMMITS" | grep -E '^docs(\([a-zA-Z0-9_-]+\))?:' > /dev/null; then
            echo "✅ New commits for docs found."
            exit 0
          else
            echo "❌ No commits for docs found."
            exit 1
          fi
