name: docs-check

on:
  workflow_call:
    outputs:
      success:
        description: "Indicates if new documentation commits were found"
        value: ${{ jobs.check.outputs.success }}

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.set-success.outputs.success }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for documentation commits
        id: set-success
        run: |
          # Get all commit messages in the current push
          COMMITS=$(git log --pretty=%s ${{ github.event.before }}..${{ github.sha }} 2>/dev/null || echo "")

          # Check if any commit includes "docs:" or "docs(anything):"
          if echo "$COMMITS" | grep -E '^docs(\([a-zA-Z0-9_-]+\))?:' > /dev/null; then
            echo "✅ New commits for docs found."
          else
            echo "❌ No commits for docs found."
          fi
