name: docs

on:
  workflow_call:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Version from Git Tag
        run: echo "VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"

      - name: Cache root node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install root dependencies
        run: npm install

      - name: Cache Docusaurus node_modules
        uses: actions/cache@v4
        with:
          path: docusaurus/node_modules
          key: ${{ runner.os }}-node-docusaurus-${{ hashFiles('docusaurus/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-docusaurus-

      - name: Install Docusaurus dependencies
        run: npm install
        working-directory: ./docusaurus

      - name: Move TypeDoc Docs to Versioned Folder
        if: github.ref == 'refs/heads/main'
        run: npm run docusaurus docs:version $VERSION
        working-directory: ./docusaurus

      - name: Move TypeDoc Docs to @next Folder
        if: github.ref == 'refs/heads/next'
        run: npm run docusaurus docs:version next
        working-directory: ./docusaurus

      - name: Build Docusaurus
        run: npm run build
        working-directory: ./docusaurus

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./docusaurus/build"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          branch: ${{ github.ref == 'refs/heads/main' && 'main' || 'next' }} # Conditionally use 'main' or 'next'
          folder: docusaurus/build
