name: on-release

on:
  workflow_call:

permissions:
  contents: read

jobs:
  onrelease:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure we fetch all tags

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Root dependencies
        run: npm install

      - name: Cache Docusaurus node_modules
        uses: actions/cache@v4
        with:
          path: docusaurus/node_modules
          key: ${{ runner.os }}-node-docusaurus-${{ hashFiles('docusaurus/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-docusaurus-

      - name: Install Docusaurus dependencies
        run: npm install
        working-directory: ./docusaurus

      - name: Get the Git tag
        run: |
          # Debug: Check the status of the repository
          git status

          # Try to get the latest tag, fallback if no tag exists
          TAG_NAME=$(git describe --tags --abbrev=0 || echo "No tags found")
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

          # Debug: Print out the list of tags
          git tag

          # Check if the tag is a pre-release (adjust logic for `next` versions)
          if [[ "$TAG_NAME" == "No tags found" ]]; then
            IS_PRERELEASE="true"
          else
            # Check if the tag contains '-next' to consider it a pre-release
            if [[ "$TAG_NAME" == *"-next"* ]]; then
              IS_PRERELEASE="true"
            else
              IS_PRERELEASE="false"
            fi
          fi

          echo "IS_PRERELEASE=$IS_PRERELEASE" >> $GITHUB_ENV

      - name: Version Docs with Docusaurus
        run: |
          # Ensure you're in the correct directory
          cd docusaurus

          # Run docs:version with 'next' for pre-releases, else use the tag name
          if [ "$IS_PRERELEASE" == "true" ]; then
            echo "Pre-release detected. Using 'next' as the version name."
            npx docusaurus docs:version next
          else
            echo "Stable release detected. Using $TAG_NAME as the version name."
            npx docusaurus docs:version "${TAG_NAME#v}"
          fi

          # Ensure versioned_docs and versioned_sidebars directories exist
          if [ -d "$PWD/versioned_docs" ] && [ -d "$PWD/versioned_sidebars" ]; then
            # Tar with both versioned_docs and versioned_sidebars at the top level
            tar -czf docs.tar.gz -C "$PWD" versioned_docs -C "$PWD" versioned_sidebars
          else
            echo "Error: versioned_docs or versioned_sidebars directories do not exist!"
            exit 1
          fi

      - name: Upload docs as release asset
        uses: softprops/action-gh-release@v2
        with:
          files: docusaurus/docs.tar.gz
          tag_name: ${{ env.TAG_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
