name: publish-docs

on:
  workflow_call:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"

      - name: Cache root node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install root dependencies
        run: npm install

      - name: Cache Docusaurus node_modules
        uses: actions/cache@v4
        with:
          path: docusaurus/node_modules
          key: ${{ runner.os }}-node-docusaurus-${{ hashFiles('docusaurus/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-docusaurus-

      - name: Install Docusaurus dependencies
        run: npm install
        working-directory: ./docusaurus

      - name: Fetch Latest Pre-Release Tag
        id: pre_release_tag
        run: |
          PRE_RELEASE_TAG=$(gh release list --json tagName,isPrerelease -q '.[] | select(.isPrerelease) | .tagName' | head -n 1)
          echo "PRE_RELEASE_TAG=$PRE_RELEASE_TAG" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch Last Stable Release Tags (With Docs)
        id: stable_release_tags
        run: |
          # Set the desired number of stable tags
          STABLE_TAGS_TOTAL=3

          # Get stable tags (not prereleases) using GitHub CLI
          STABLE_TAGS=$(gh release list --json tagName,isPrerelease -q '.[] | select(.isPrerelease | not) | .tagName' | grep -v '\-next' | head -n $STABLE_TAGS_TOTAL)

          # If no tags found, make STABLE_TAGS an empty array
          if [ -z "$STABLE_TAGS" ]; then
            STABLE_TAGS=""
          else
            # Convert to a comma-separated string
            STABLE_TAGS=$(echo "$STABLE_TAGS" | tr '\n' ',')
            STABLE_TAGS="${STABLE_TAGS%,}"  # Remove trailing comma if present
          fi

          # Set the stable tags environment variable
          echo "STABLE_TAGS=$STABLE_TAGS" >> $GITHUB_ENV

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download and Extract Docs for Each Selected Tag
        run: |
          mkdir -p docusaurus/versioned_docs docusaurus/versioned_sidebars

          # Fetch and extract pre-release docs (already named version-next)
          if [ -n "$PRE_RELEASE_TAG" ]; then
            gh release view "$PRE_RELEASE_TAG" --json assets -q '.assets[].name' | grep -q "docs.tar.gz" && {
              gh release download "$PRE_RELEASE_TAG" --pattern "docs.tar.gz" --dir .
              # Extract versioned_docs and versioned_sidebars from tarball
              tar -xzf docs.tar.gz -C docusaurus versioned_docs/version-next
              tar -xzf docs.tar.gz -C docusaurus versioned_sidebars
              rm docs.tar.gz
            } || echo "Skipping $PRE_RELEASE_TAG: No docs.tar.gz found"
          fi

          # Fetch and extract stable docs
          for TAG in $(echo "$STABLE_TAGS" | tr ',' '\n'); do
            CLEAN_TAG=${TAG#v} # Remove leading 'v' if present
            gh release view "$TAG" --json assets -q '.assets[].name' | grep -q "docs.tar.gz" && {
              gh release download "$TAG" --pattern "docs.tar.gz" --dir .
              # Extract versioned_docs and versioned_sidebars from tarball
              tar -xzf docs.tar.gz -C docusaurus versioned_docs/version-$CLEAN_TAG
              tar -xzf docs.tar.gz -C docusaurus versioned_sidebars
              rm docs.tar.gz
            } || echo "Skipping $TAG: No docs.tar.gz found"
          done

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create versions.json
        run: |
          if [ -n "$PRE_RELEASE_TAG" ]; then
            # Initialize versions.json with "next" if PRE_RELEASE_TAG exists
            echo '["next"]' > docusaurus/versions.json
            if [ -n "$STABLE_TAGS" ]; then
              # Convert STABLE_TAGS into a JSON array, removing the 'v' prefix from each tag
              STABLE_TAGS_JSON=$(echo "$STABLE_TAGS" | tr ',' '\n' | jq -R . | jq -s 'map(sub("^v"; ""))')
              # Append stable versions after "next"
              echo "$STABLE_TAGS_JSON" | jq -c '. | ["next"] + .' > docusaurus/versions.json
            fi
          else
            if [ -n "$STABLE_TAGS" ]; then
              # Convert STABLE_TAGS into a JSON array, removing the 'v' prefix
              STABLE_TAGS_JSON=$(echo "$STABLE_TAGS" | tr ',' '\n' | jq -R . | jq -s 'map(sub("^v"; ""))')
              echo "$STABLE_TAGS_JSON" > docusaurus/versions.json
            else
              echo '[]' > docusaurus/versions.json
            fi
          fi

      - name: Check versions.json
        run: cat ./docusaurus/versions.json

      - name: Build Docusaurus
        run: npm run build
        working-directory: ./docusaurus

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./docusaurus/build"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages
          folder: docusaurus/build
