name: pull-requests

on:
  pull_request:
    branches:
      - main
      - next

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  code:
    name: Run Code Validation
    uses: ./.github/workflows/code-validation.yml

  unit_tests:
    name: Run Unit Tests
    uses: ./.github/workflows/unit-tests.yml
    secrets: inherit
    needs:
      - code
    if: success()
