name: Requests

on:
  pull_request:
    branches:
      - main
      - next

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  code:
    name: Code Validation
    uses: ./.github/workflows/code-validation.yml

  tests:
    name: Test Runner
    uses: ./.github/workflows/test.yml
    secrets: inherit
    needs:
      - validate_code
    if: success()
